# Generated by Django 4.2.20 on 2025-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_choice_choice_alter_question_correct_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
