# Generated by Django 4.2.20 on 2025-08-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_choice_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.education'),
        ),
    ]
